adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp
app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(urls)),
    path('', views.index, name='index'),
    path('contacts/', views.contacts, name='contacts'),
]

geekshop/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.products, name='products'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import views
from django.conf import settings
from django.conf.urls.static import static
from authapp import urls as authapp_urls
from basketapp import urls as basketapp_urls
from adminapp import urls as adminapp_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(authapp_urls, namespace='auth'), name='auth'),
    path('products/', include(urls, namespace='products'), name='products'),
    path('', views.index, name='index'),
    path('contacts/', views.contacts, name='contacts'),
    path('basket/', include(basketapp_urls, namespace='basket'), name='basket'),
    path('admin_staff/', include(adminapp_urls, namespace='admin_staff'), name='admin_staff'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/geekshop/geekshop/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'geekshop/index.html')


def contacts(request):
    return render(request, 'geekshop/contact.html')

django/geekshop/mainapp/views.py
from django.shortcuts import render


def products(request):
    return render(request, 'mainapp/products.html')

geekshop/geekshop/views.py
from django.shortcuts import render


def index(request):
    title = 'главная'

    context = {
        'title': title,
    }

    return render(request, 'geekshop/index.html', context=context)


def contacts(request):
    title = 'контакты'

    context = {
        'title': title,
    }

    return render(request, 'geekshop/contact.html', context=context)

geekshop/mainapp/views.py
from django.shortcuts import render


def products(request):
    title = 'продукты'

    links_menu = [
        {'href': 'mainapp:products', 'name': 'все'},
        {'href': 'mainapp:products', 'name': 'дом'},
        {'href': 'mainapp:products', 'name': 'офис'},
        {'href': 'mainapp:products', 'name': 'модерн'},
        {'href': 'mainapp:products', 'name': 'классика'},
    ]

    context = {
        'links_menu': links_menu,
        'title': title,
    }

    return render(request, 'mainapp/products.html', context=context)

geekshop/views.py
from django.shortcuts import render
from mainapp.models import Product
from basketapp.models import Basket


def index(request, pk=None):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    title = 'главная'
    products = Product.objects.all()[:4]

    context = {
        'title': title,
        'products': products,
        'basket': basket,
    }

    return render(request, 'geekshop/index.html', context=context)


def contacts(request):
    title = 'контакты'

    context = {
        'title': title,
    }

    return render(request, 'geekshop/contact.html', context=context)

geekshop/templates/includes/inc_main_menu.html
<div class="header d-flex justify-content-start">
    <div class="col-3">
        <a href="{% url 'index'%}" class="logo"></a>
    </div>
    <div class="col-7">
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="active">домой</a></li>
        <li><a href="{% url 'products:products' %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}">контакты</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
        {% endif %}
        {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin_staff:users' %}">админка</a>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
              <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
              <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
    </div>
    <div class="col-2">
        <a href="#" class="search"></a>
        {% if basket %}
        <a href="{% url 'basket:view' %}" class="fa fa-shopping-basket basket">
            <span>
                {{ basket.0.total_cost|floatformat:0 }} руб
                {{ basket.0.total_quantity }} шт.
            </span>
        </a>
        {% endif %}
        </div>
</div>